Camera: {Focal: 13.971313932573906, High: 650.0}
Center: {Camera_high: 620, Center_X: 318, Center_Y: 255, Front: 270, Horizon: 100,
  Inner: 35, Outer: 228, X: 308, Y: 266}
FPS: 17
HSV:
  Ball: [0, 30, 30, 94, 30, 100]
  Blue: [203, 236, 82, 100, 0, 100]
  Green: [120, 209, 52, 86, 19, 63]
  White: [0, 359, 0, 22, 0, 23]
  Yellow: [32, 80, 29, 100, 0, 100]
  black: {angle: 3, gray: 26}
  white: {angle: 3, gray: 120}
Parameterbutton: 7
SCAN: {Angle_Near_Gap: 4, Angle_range_1: 2, Angle_range_2_3: 2, Dont_Search_Angle_1: 333,
  Dont_Search_Angle_2: 91, Dont_Search_Angle_3: 204, Magn_Far_End: 226, Magn_Far_Start: 159,
  Magn_Middle_Start: 94, Magn_Near_Gap: 2, Magn_Near_Start: 33}
blackItem: {angle: 3, gray: 40}
whiteline: {angle: 4, gray: 100}
